package com.example.lab8_cli.StatsBundle;

import java.util.ListResourceBundle;

public class StatsBundle_vi_VN extends ListResourceBundle {

    private final Object[][] resources = {
            {"UsernameLabel","Tên người dùng"},
            {"PasswordLabel", "Mật khẩu"},
            {"RefreshButton","Tải lại"},
            {"InfoButton", "Thông tin"},
            {"AddButton","Thêm"},
            {"UpdateButton","Cập nhật"},
            {"RemoveButton","Loại bỏ"},
            {"ClearButton","Dọn dẹp"},
            {"ExecuteScriptButton", "Mã"},
            {"AddIfMaxButton","Thêm nếu lớn nhất"},
            {"RemoveGreaterButton","Xóa lớn nhất"},
            {"CountLessThanFuelTypeButton", "Đếm kém hơn loại nhiên liệu"},
            {"FilterLessThanFuelConsumptionButton","Lọc kém hơn nhiên liêu tiêu thụ"},
            {"GroupCountingByCapacityButton","Nhóm bởi dung tích"},
            {"RefreshButtonTooltip","Cập nhật đồ thị và bảng"},
            {"InfoButtonTooltip","Hiện thị thông tin về bảng"},
            {"AddButtonTooltip","Thêm phần tử vào bộ sưu tập"},
            {"UpdateButtonTooltip","Cập nhật phần tử"},
            {"RemoveButtonTooltip","Xóa phần tử khỏi bộ sưu tập"},
            {"ClearButtonTooltip","Xóa bộ sưu tập"},
            {"ExecuteButtonTooltip","Thực thi mã từ tập tin"},
            {"AddIfMaxButtonTooltip","Thêm phần tử nếu nó là lớn nhất"},
            {"RemoveGreaterButtonTooltip","Xóa các phần tử lớn hơn phần tử đã cho"},
            {"IdColumn","ID"},
            {"OwnerColumn","Chủ sở hữu"},
            {"CreationDateColumn","Ngày tạo"},
            {"NameColumn","Tên"},
            {"CoordinatesXColumn","X"},
            {"CoordinatesYColumn","Y"},
            {"EnginePowerColumn","Sức mạnh động cơ"},
            {"CapacityColumn","Dung tích"},
            {"FuelConsumptionColumn","Nhiên liệu tiêu thụ"},
            {"FuelTypeColumn","Loại nhiên liệu"},
            {"TableTab","Bảng"},
            {"CanvasTab","Đồ thị"},
            {"EnterButton","Nhập"},
            {"NameEmptyException","Tên không được trống"},
            {"CoordinatesXFormatException","X phải là số!"},
            {"CoordinatesYFormatException","Y phải là số!"},
            {"UpdateButtonSelectionException","Chọn phương tiện cập nhật"},
            {"RemoveButtonSelectionException","Chọn phương tiện để xóa!"},
            {"RemoveGreaterButtonSelectionException","Chọn phương tiện để xóa lớn hơn!"},
            {"EnterName","Nhập tên:"},
            {"NameNotIdentifiedException","Tên không được công nhận"},
            {"UnexpectedException","Lỗi không mong muốn!"},
            {"EnterX","Nhập tọa độ X:"},
            {"XNotIdentifiedException","Tọa độ X không được công nhận"},
            {"XMustBeNumberException","Tọa độ X phải là số"},
            {"EnterY","Nhập tọa độ Y< {0}:"},
            {"YNotIdentifiedException","Y Không được công nhận"},
            {"YMustBeNumberException","Tọa độ Y Phải được biểu diễn bằng số"},
            {"YMustBeLessException","Y phải không quá{0}!"},
            {"ScriptRecursionException","Mã không được gọi đệ quy"},
            {"IncorrectInputInScriptException","Thực hi mã bị ngắt"},
            {"CommandNotFoundException","Command'' {0}''not found.Type''help'' for reference."},
            {"Using","Use:'' {0}''"},
            {"ClientException","Ứng dụng khách không thể khởi động"},
            {"EndWorkOfClient","Ứng dụng khách đã dừng"},
            {"EndWorkOfClientException","Lỗi đã xảy ra khi đan thiết lập kết nối đến server!"},
            {"EndRunningWorkOfClientException","Không thể chấm dứt kết nối chưa được thiết lập!"},
            {"DataSendingException","Đã xảy ra lỗi khi gửi dữ liệu đến máy chủ!"},
            {"DataReadingException","Đã xảy ra lỗi khi đọc dữ liệu nhận được!"},
            {"EndConnectionToServerException","Kết nối với máy chủ bị hỏng!"},
            {"ConnectionToServerComplete","Đã thiết lập kết nối với máy chủ!"},
            {"TryCommandLater","Cố gắng lặp lại lệnh sau."},
            {"TryAuthLater","Cố gắng lặp lại xác thực sau."},
            {"ConnectionToServer","Đang kết nối với máy chủ ..."},
            {"ServerAddressException","Địa chỉ máy chủ không được nhập chính xác!"},
            {"ConnectionToServerException","Đã xảy ra lỗi khi kết nối với máy chủ!"},
            {"CountLessThanFuelTypeButtonTooltip", "Đếm số phần tử ít hơn loại nhiên liệu đã cho"},
            {"FilterLessThanFuelConsumptionButtonTooltip", "Lọc phần tử ít hơn mức tiêu thụ nhiên liệu đã cho"},
            {"GroupCountingByCapacityButtonTooltip", "Đếm nhóm theo dung lượng"},
            {"RefreshButtonTooltip", "Làm mới"},
            {"RegisterCheckbox", "Hộp đăng ký"},
            {"SignInButton", "Đăng nhập"},
            {"Summit", "Xác nhận"},
            {"Connected", "Đã kết nối"},
            {"NotConnected", "Chưa kết nối"}

    };

    @Override
    protected Object[][] getContents() {
        return resources;
    }
}