package com.example.lab8_cli.StatsBundle;

import java.util.ListResourceBundle;

public class StatsBundle_es_EC extends ListResourceBundle {

    private final Object[][] resources = {
            {"UsernameLabel","nombre de usuario"},
            {"PasswordLabel", "clave"},
            {"RefreshButton","Actualizar"},
            {"InfoButton", "Información"},
            {"AddButton","Agregar"},
            {"UpdateButton","Actualizar"},
            {"RemoveButton","Remover"},
            {"ClearButton","Claro"},
            {"ExecuteScriptButton", "Guion"},
            {"AddIfMaxButton","Añadir si máx."},
            {"RemoveGreaterButton","Quitar mayor"},
            {"CountLessThanFuelTypeButton", "Cuente menos que FuelType"},
            {"FilterLessThanFuelConsumptionButton","Filtrar menos que el consumo de combustible"},
            {"GroupCountingByCapacityButton","Conteo de grupos por capacidad"},
            {"RefreshButtonTooltip","Actualizar lienzo y tabla"},
            {"InfoButtonTooltip","Mostrar información sobre la colección."},
            {"AddButtonTooltip","Añadir un nuevo elemento a la colección."},
            {"UpdateButtonTooltip","Actualizar un elemento en la colección"},
            {"RemoveButtonTooltip","Eliminar un elemento de la colección."},
            {"ClearButtonTooltip","Limpiar la colección"},
            {"ExecuteButtonTooltip","Ejecutar script desde un archivo"},
            {"AddIfMaxButtonTooltip","Agregue un nuevo elemento si su valor es mayor que los más grandes"},
            {"RemoveGreaterButtonTooltip","Eliminar todos los elementos que son más altos que los seleccionados"},
            {"IdColumn","ID"},
            {"OwnerColumn","Dueño"},
            {"CreationDateColumn","Fecha de creación"},
            {"NameColumn","Nombre"},
            {"CoordinatesXColumn","X"},
            {"CoordinatesYColumn","Y"},
            {"EnginePowerColumn","Potencia del motor"},
            {"CapacityColumn","Capacidad"},
            {"FuelConsumptionColumn","El consumo de combustible"},
            {"FuelTypeColumn","Tipo de combustible"},
            {"TableTab","Mesa"},
            {"CanvasTab","Lienzo"},
            {"EnterButton","Enter"},
            {"NameEmptyException","Nombre no puede estar vacío!"},
            {"CoordinatesXFormatException","¡X debe ser un número!"},
            {"CoordinatesYFormatException","¡Debe ser un número!"},
            {"UpdateButtonSelectionException","¡Seleccione el vehículo para actualizar!"},
            {"RemoveButtonSelectionException","Seleccione el vehículo para eliminar!"},
            {"RemoveGreaterButtonSelectionException","Seleccione el vehículo para eliminar mayor!"},
            {"EnterName","Ingresa un nombre:"},
            {"NameNotIdentifiedException","¡No se reconoce el nombre!"},
            {"UnexpectedException","¡Error inesperado!"},
            {"EnterX","Introduzca la coordenada X:"},
            {"XNotIdentifiedException","¡La coordenada X no se reconoce!"},
            {"XMustBeNumberException","¡La coordenada X debe ser un número!"},
            {"EnterY","Introduzca la coordenada Y:"},
            {"YNotIdentifiedException","¡No reconocido!"},
            {"YMustBeNumberException","¡La coordenada Y debe estar representada por un número!"},
            {"YMustBeLessException","¡Y no debe exceder {0}!"},
            {"ScriptRecursionException","¡Los scripts no se pueden llamar recursivamente!"},
            {"IncorrectInputInScriptException","¡Se interrumpe la ejecución del script!"},
            {"CommandNotFoundException","Comando'' {0}''no encontrado. Escriba''ayuda'' como referencia."},
            {"Using","Use:'' {0}''"},
            {"ClientException","¡No se puede iniciar el cliente!"},
            {"EndWorkOfClient","El cliente se ha detenido."},
            {"EndWorkOfClientException","¡Se ha producido un error al intentar finalizar la conexión con el servidor!"},
            {"EndRunningWorkOfClientException","¡No se puede terminar la conexión aún no establecida!"},
            {"DataSendingException","¡Se ha producido un error al enviar datos al servidor!"},
            {"DataReadingException","¡Se ha producido un error al leer los datos recibidos!"},
            {"EndConnectionToServerException","¡Conexión con el servidor averiada!"},
            {"ConnectionToServerComplete","¡Conexión con el servidor establecida!"},
            {"TryCommandLater","Intente repetir el comando más tarde."},
            {"TryAuthLater","Intente repetir la autenticación más tarde."},
            {"ConnectionToServer","Conectando con el servidor..."},
            {"ServerAddressException","¡La dirección del servidor no se ha introducido correctamente!"},
            {"ConnectionToServerException","¡Se ha producido un error al conectar con el servidor!"},
            {"CountLessThanFuelTypeButtonTooltip", "Count the number of vehicle has fuel type less than the given one"},
            {"FilterLessThanFuelConsumptionButtonTooltip", "Filter the vehicle that less than the given fuel type"},
            {"GroupCountingByCapacityButtonTooltip", "Group count by capacity"},
            {"RefreshButtonTooltip", "refresh"},
            {"RegisterCheckbox", "Regiter box"},
            {"SignInButton", "Sign in "},
            {"Summit", "Summit"},
            {"Connected", "Connected"},
            {"NotConnected", "NotConnected"}
    };

    @Override
    protected Object[][] getContents() {
        return resources;
    }
}