package com.example.lab8_cli.StatsBundle;

import java.util.ListResourceBundle;

public class StatsBundle_hu_HU extends ListResourceBundle {

    private final Object[][] resources = {
            {"UsernameLabel","felhasználónév"},
            {"PasswordLabel", "Jelszó"},
            {"RefreshButton","Frissítés"},
            {"InfoButton", "Info"},
            {"AddButton","Hozzáadás"},
            {"UpdateButton","Frissítés"},
            {"RemoveButton","Távolítsa el"},
            {"ClearButton","Egyértelmű"},
            {"ExecuteScriptButton", "Forgatókönyv"},
            {"AddIfMaxButton","Add hozzá, ha max"},
            {"RemoveGreaterButton","Távolítsa el a nagyobbat"},
            {"CountLessThanFuelTypeButton", "Számoljon kevesebbet, mint az üzemanyag típusa"},
            {"FilterLessThanFuelConsumptionButton","Szűrj kevesebbet, mint az üzemanyag-fogyasztás"},
            {"GroupCountingByCapacityButton","Csoportszámlálás kapacitás szerint"},
            {"RefreshButtonTooltip","Frissítse a vászont és az asztalt"},
            {"InfoButtonTooltip","Információk megjelenítése a gyűjteményről"},
            {"AddButtonTooltip","Új elem hozzáadása a gyűjteményhez"},
            {"UpdateButtonTooltip","Frissítsen egy elemet a gyűjteményben"},
            {"RemoveButtonTooltip","Távolítson el egy elemet a gyűjteményből"},
            {"ClearButtonTooltip","Törölje a gyűjteményt"},
            {"ExecuteButtonTooltip","Parancsfájl végrehajtása egy fájlból"},
            {"AddIfMaxButtonTooltip","Adjon hozzá új elemet, ha annak értéke nagyobb, mint a legnagyobbak"},
            {"RemoveGreaterButtonTooltip","Távolítsa el az összes olyan elemet, amely magasabb a kijelöltnél"},
            {"IdColumn","ID"},
            {"OwnerColumn","Tulajdonos"},
            {"CreationDateColumn","Létrehozás dátuma"},
            {"NameColumn","Név"},
            {"CoordinatesXColumn","X"},
            {"CoordinatesYColumn","Y"},
            {"EnginePowerColumn","Motor teljesítmény"},
            {"CapacityColumn","Kapacitás"},
            {"FuelConsumptionColumn","Üzemanyag fogyasztás"},
            {"FuelTypeColumn","Üzemanyagtípus"},
            {"TableTab","asztal"},
            {"CanvasTab","Vászon"},
            {"EnterButton","Belép"},
            {"NameEmptyException","A név nem lehet üres!"},
            {"CoordinatesXFormatException","X-nek számnak kell lennie!"},
            {"CoordinatesYFormatException","Y számnak kell lennie!"},
            {"UpdateButtonSelectionException","Válassza ki a frissíteni kívánt járművet!"},
            {"RemoveButtonSelectionException","Válassza ki az eltávolítani kívánt járművet!"},
            {"RemoveGreaterButtonSelectionException","Válassza ki az eltávolítani kívánt járművet!"},
            {"EnterName","Írjon be egy nevet:"},
            {"NameNotIdentifiedException","A név nem ismerhető fel!"},
            {"UnexpectedException","Unexpected error!"},
            {"EnterX","Adja meg az X koordinátát:"},
            {"XNotIdentifiedException","Az X koordináta nem ismerhető fel!"},
            {"XMustBeNumberException","Az X koordinátának számnak kell lennie!"},
            {"EnterY","Írja be az Y koordinátát< {0}:"},
            {"YNotIdentifiedException","I Nem ismerik fel!"},
            {"YMustBeNumberException","Az Y-koordinátát számmal kell ábrázolni!"},
            {"YMustBeLessException","Y nem haladhatja meg a(z) {0} értéket!"},
            {"ScriptRecursionException","A szkriptek nem hívhatók rekurzív módon!"},
            {"IncorrectInputInScriptException","A szkript végrehajtása megszakadt!"},
            {"Using","Use:'' {0}''"},
            {"ClientException","A kliens nem indítható!"},
            {"EndWorkOfClient","Az ügyfél leállt."},
            {"EndWorkOfClientException","Hiba történt, amikor megpróbálta megszakítani a kapcsolatot a szerverrel!"},
            {"EndRunningWorkOfClientException","A kapcsolat még nem bontható meg!"},
            {"DataSendingException","Hiba történt az adatok szerverre küldésekor!"},
            {"DataReadingException","Hiba történt a kapott adatok beolvasása közben!"},
            {"EndConnectionToServerException","Megszakadt a kapcsolat a szerverrel!"},
            {"ConnectionToServerComplete","A kapcsolat létrejött a szerverrel!"},
            {"TryCommandLater","Próbálja meg később megismételni a parancsot."},
            {"TryAuthLater","Próbálja meg később megismételni a hitelesítést."},
            {"ConnectionToServer","Csatlakozás a szerverhez..."},
            {"ServerAddressException","A szerver címe nincs helyesen megadva!"},
            {"ConnectionToServerException","Hiba történt a szerverhez való csatlakozáskor!"},
            {"CountLessThanFuelTypeButtonTooltip", "Count the number of vehicle has fuel type less than the given one"},
            {"FilterLessThanFuelConsumptionButtonTooltip", "Filter the vehicle that less than the given fuel type"},
            {"GroupCountingByCapacityButtonTooltip", "Group count by capacity"},
            {"RefreshButtonTooltip", "refresh"},
            {"RegisterCheckbox", "Regiter box"},
            {"SignInButton", "Sign in "},
            {"Summit", "Summit"},
            {"Connected", "Connected"},
            {"NotConnected", "NotConnected"}
    };

    @Override
    protected Object[][] getContents() {
        return resources;
    }
}